<!-- - - - - - - - - - - - - Slider - - - - - - - - - - - - - - - -->
<?php require 'module/Users/view/users/utils/index_label.php';?>
<div class="wrap">
	<div class="slider">
		<h2 class="mycenter" style="width: 320px;"><?php echo $labels['about4Helper']?></h2>
		<p class="mycenter" style="width: 800px; font-size: 200%;"><?php echo $labels['aboutUs']?></p>
	</div>
	<!--/ .slider-->
</div>
<!--/ .wrap-->

<!-- - - - - - - - - - - - - end Slider - - - - - - - - - - - - - - -->
