<!-- - - - - - - - - - - - - Slider - - - - - - - - - - - - - - - -->
<?php require 'module/Users/view/users/utils/index_label.php';?>
<div class="wrap">
	<div class="slider">
		<h2 class="mycenter" style="width: 350px;"><?php echo $labels['helpSupport']?></h2>
		<p class="mycenter infoShow"><?php echo $labels['helpContent']?></p>
		<div class="mycenter infoShow">
			<div><?php echo $labels['mailHint']?></div>
			<div class="ui-state-default ui-corner-all"
				style="width: 20px; margin-top: 10px">
				<a href="mailto:support@4helper.com?subject=<?php echo $labels['needHelp']?>"><span
					class="ui-icon ui-icon-mail-closed"></span></a>
			</div>
		</div>
	</div>
	<!--/ .slider-->
</div>
<!--/ .wrap-->

<!-- - - - - - - - - - - - - end Slider - - - - - - - - - - - - - - -->
