<!-- - - - - - - - - - - - - Slider - - - - - - - - - - - - - - - -->
<?php require 'module/Users/view/users/utils/index_label.php';?>
<div class="wrap">
	<div class="slider">
		<h2 class="mycenter" style="width: 200px;">Investers</h2>
		<p class="mycenter infoShow">We are funded by private investors.If you
			need further information, write us and we’ll be happy to answer your
			questions.</p>
		<div class="mycenter infoShow">
			<div>Please email your questions :</div>
			<div class="ui-state-default ui-corner-all"
				style="width: 20px; margin-top: 10px">
				<a href="mailto:investors@4helper.com?subject=About Investor"><span
					class="ui-icon ui-icon-mail-closed"></span></a>
			</div>
		</div>
	</div>
	<!--/ .slider-->
</div>
<!--/ .wrap-->

<!-- - - - - - - - - - - - - end Slider - - - - - - - - - - - - - - -->
