<!-- - - - - - - - - - - - - Slider - - - - - - - - - - - - - - - -->
<?php require 'module/Users/view/users/utils/index_label.php';?>
<div class="wrap">
	<div class="slider">
		<h2 class="mycenter" style="width: 400px;"><?php echo $labels['lookForTalent']?></h2>
		<p class="mycenter infoShow"><?php echo $labels['contentOfJoin']?></p>
		<div class="mycenter infoShow">
			<div>Please email your resume :</div>
			<div class="ui-state-default ui-corner-all" style="width: 20px; margin-top: 10px"><a
				href="mailto:hr@4helper.com?subject=Apply Job"><span
				class="ui-icon ui-icon-mail-closed"></span></a></div>
		</div>
	</div>
	<!--/ .slider-->
</div>
<!--/ .wrap-->

<!-- - - - - - - - - - - - - end Slider - - - - - - - - - - - - - - -->
