<!-- - - - - - - - - - - - - Slider - - - - - - - - - - - - - - - -->
<?php require 'module/Users/view/users/utils/index_label.php';?>
<div class="wrap">
	<div class="slider">
		<h2 class="mycenter" style="width: 400px;">Privacy and Terms</h2>
		<div class="mycenter infoShow">
			<h4>Our data privacy policy</h4>
			<h5>Information we collect and store:</h5>
			<p>We collect and store the text, information, targets and files you
				upload or access with the 4Helper Service. When you access
				4Helper, we may automatically record information from your
				device, its software, and your activity using the service. This may
				include your device’s IP address, browser type, the web page visited
				before you came to our website, location, locale preferences, date
				and time stamps and other metadata concerning your interactions with
				the service.</p>
			<h5>Our Use of Your Personal Information:</h5>
			<p>In the course of using the Service, we may collect personal
				information that can be used to contact or identify you (“Personal
				Information”). Personal Information is or may be used: (i) to
				provide and improve our Service, (ii) to administer your use of the
				Service, (iii) to better understand your needs and interests, (iv)
				to personalize and improve your experience, and (v) to provide or
				offer software updates and product announcements.</p>
			<h4>Terms</h4>
			<p>Your use of the Service, including any content, information or
				functionality contained within it, is provided “as is” and “as
				available” with no representations or warranties of any kind, either
				expressed or implied, including but not limited to, the implied
				warranties of merchantability, fitness for a particular purpose, and
				non-infringement. You assume total responsibility and risk for your
				use of this Service. You agree not to resell, duplicate, reproduce
				or exploit any part of the Service without the express written
				permission of 4Helper. You may not use the Service to store,
				host, or send unsolicited email (spam). You understand that the
				Service can be used for transmission of your Content, and that
				during processing, your Content, including names, target details and
				account information may be transferred unencrypted over the
				internet. You may not use the Service to transmit any viruses,
				worms, or malicious content. 4Helper makes no warranties
				regarding (i) your ability to use the Service, (ii) your
				satisfaction with the Service, (iii) that the Service will be
				available at all times, uninterrupted, and error-free (iv), the
				accuracy of mathematical calculations performed by the Service, and
				(v) that bugs or errors in the Service will be corrected.
				4Helper, its affiliates and its sponsors are neither responsible
				nor liable for any direct, indirect, incidental, consequential,
				special, exemplary, punitive, or other damages arising out of or
				relating in any way to your use of the Service. Your sole remedy for
				dissatisfaction with the Service is to stop using the Service.
				4Helper reserves the right to use the name/logo of the customers on
				our Software/Website/Marketing Materials. If any provision of the
				Terms Of Service is held invalid or otherwise unenforceable, the
				enforceability of the remaining provisions shall not be impaired
				thereby. The failure of 4Helper to exercise any right provided for
				herein shall not be deemed a waiver of any right hereunder. The
				Terms Of Service sets forth the entire understanding between you and
				4Helper as to the Service and supersedes any prior agreements
				between you and 4Helper (including, but not limited to, prior
				versions of the Terms Of Service). Any questions regarding the Terms
				Of Service should be addressed to terms@4helper.com.</p>
		</div>
		<div class="mycenter infoShow">
			<div>Please email your questions :</div>
			<div class="ui-state-default ui-corner-all"
				style="width: 20px; margin-top: 10px">
				<a href="mailto:terms@4helper.com?subject=About Terms"><span
					class="ui-icon ui-icon-mail-closed"></span></a>
			</div>
		</div>
	</div>
	<!--/ .slider-->
</div>
<!--/ .wrap-->

<!-- - - - - - - - - - - - - end Slider - - - - - - - - - - - - - - -->
