<?php
// set language in session according navigator
require 'module/Users/view/users/utils/index_label.php';
$this->headTitle()->prepend($labels['register']);
?>

<script src="/js/register.js" type="text/javascript"></script>
<script src="/js/captcha.js" type="text/javascript"></script>

<!-- copy from captcha -->
<?php

// Make the page validate
ini_set('session.use_trans_sid', '0');

// Include the random string file
// require 'captcha/rand.php';
// Create a random string, leaving out 'o' to avoid confusion with '0'
$char = strtoupper(substr(str_shuffle('abcdefghjkmnpqrstuvwxyz'), 0, 4));

// Concatenate the random string onto the random numbers
// The font 'Anorexia' doesn't have a character for '8', so the numbers will only go up to 7
// '0' is left out to avoid confusion with 'O'
$str = rand(1, 7) . rand(1, 7) . $char;

// Begin the session
session_start();

// Set the session contents
$_SESSION['captcha_id'] = $str;

?>

<!-- end the captcha -->

<div class="banner">
	<h1><?php echo $labels[title3]?></h1>
</div>
<section class="register">

	<div class="clearfix">
		<div class="sign-up">
			<div class="signup-box">
				<div class="error mycenter" id="registerError"
					style="width: 150px;"><?php echo $labels[registerError]?></div>
				<div class="success mycenter" id="registerSuccess"
					style="width: 200px;"><a href="/users/login"><?php echo $labels['successRegister']?></a></div>
        <?php
        $form = $this->form;
        $form->prepare();
        $form->setAttribute('action', $this->url(NULL, array(
            'controller' => 'Register',
            'action' => 'process'
        )));
        $form->setAttribute('method', 'post');
        $form->setAttribute('autocomplete', 'off');
        
        echo $this->form()->openTag($form);
        ?>
        <fieldset>

					<legend>
						<strong><?php echo $labels[name]?></strong>
					</legend>
            
                <?php
                echo $this->formElement($form->get('first_name'));
                echo $this->formElementErrors($form->get('first_name'));
                ?>
                <br>
                <?php
                echo $this->formElement($form->get('last_name'));
                echo $this->formElementErrors($form->get('last_name'));
                ?>
           
        </fieldset>

				<fieldset>
             <?php
            echo $this->formElement($form->get('email'));
            echo $this->formElementErrors($form->get('email'));
            ?>
                
            
        </fieldset>
				<fieldset>
					<select name="language">
					<?php
    
    if ($_SESSION['language'] == 'zh') {
        echo "<option value='zh'>中文</option>
						<option value='en'>English</option>";
    } else {
        echo "<option value='en'>English</option>
						<option value='zh'>中文</option>";
    }
    ?>
					</select> <span><?php echo $labels['languageSet']?></span>
				</fieldset>
				<br>
				<fieldset>
             <?php
            echo $this->formElement($form->get('password'));
            echo $this->formElementErrors($form->get('password'));
            ?>            
        </fieldset>

				<fieldset>
             <?php
            echo $this->formElement($form->get('confirm_password'));
            echo $this->formElementErrors($form->get('confirm_password'));
            ?>   
        </fieldset>
				<table>
					<tr>

						<td>
							<div id="captchaimage">
								<a href="" id="refreshimg"
									title="<?php echo $labels[changeImg]?>"><img
									src="/captcha/images/image.php?<?php echo time(); ?>"
									alt="<?php echo $labels[click]?>" id="captcha_image" /></a>
							</div>
						</td>
					</tr>
					<tr>
						<td><input type="text" maxlength="6" class="form-element"
							name="captcha" id="captcha"
							placeholder="<?php echo $labels[captcha]?>" /></td>
					</tr>
					<tr>
						<td class="field">
							<div id="termswrap">
								<input id="terms" type="checkbox" name="terms" checked="checked" />
								<label id="lterms" for="terms"><strong><?php echo $labels[accept]?></strong><a target="view_window"
									href="/info/terms"><?php echo $labels[terms]?></a></label>
							</div> <!-- /termswrap -->
						</td>
					</tr>
				</table>

        <?php
        echo $this->formElement($form->get('submit'));
        echo $this->formElementErrors($form->get('submit'));
        ?>
        
        		
        <?php echo $this->form()->closeTag()?>
        </div>
			<div style="width: 20px;" class="mycenter">
				<img id="loadingImg" alt="loading"
					src="/images/loading.gif">
			</div>

		</div>
	</div>
</section>
<p></p>
