<?php
echo $this->doctype();
require 'module/Users/view/users/utils/index_label.php';

?>

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php echo $this->headTitle($this->translate($labels[logo]))->setSeparator(' - ')->setAutoEscape(false)?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')?>
        <meta name="description"
	content=<?php echo $labels[shareInfo]; ?> />
<meta name="author" content="ttruus" />
<meta name="keywords"
	content="share, targets, communication, share target, 分享, 目标, 沟通, 目标分享, 分享目标" />
<meta name="description"
	content="Improve communication with targts, have fun in work and manage targets" />
<meta name="description" content="提高基于目标的有效沟通，增加工作中的趣味" />
<link type="text/css" rel="stylesheet" media="screen"
	href="/css/1140.css">
<link type="text/css" rel="stylesheet" media="screen"
	href="/css/start/jquery-ui-1.10.3.custom.css">
<link type="text/css" rel="stylesheet" media="screen"
	href="/css/style.css">
<!-- scripts -->
	     <?php
    
    echo $this->headScript()
        ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array(
        'conditional' => 'lt IE 9'
    ))
        ->prependFile($this->basePath() . '/js/jquery-1.9.1.js')?>
         <script src="/js/jquery-ui-1.10.3.custom.js"
	type="text/javascript"></script>


<!-- customer style by Yuhai -->
<link href="/css/myStyle.css" rel="stylesheet" type="text/css" />

<!--  ttruus ico -->
        <?php
        
        echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/images/h.ico'
        ))?>

    </head>
<body class="h-style-1 text-1" hidden="hidden">
	<!-- js disable label -->
	<div id="jscheck">
		<br>
		<h1 class="error"><?php echo $labels['noJs']?></h1>
	</div>
	<div id="jsHtml5Ok" hidden="hidden">
		<!-- - - - - - - - - - - - - - Top Panel - - - - - - - - - - - - - - - - -->
		<div class="top-line clearfix">

			<div class="topcenter">
				<ul id="topleft">
					<li class="ui-state-default ui-corner-all"
						title="<?php echo $labels['home']?>"><a href="/"><span
							class="ui-icon ui-icon-home"></span></a></li>
				</ul>

				<ul id="topright">
					<li><a href="/users/register">| <?php echo $labels[register]?> </a>
					</li>
					<li><a href="/users/login"><?php echo $labels[login]?> </a></li>

				</ul>
			</div>

		</div>
		<!--/ .top-line-->
		<!-- - - - - - - - - - - - - end Top Panel - - - - - - - - - - - - - - - -->



		<!-- - - - - - - - - - - - - - Header - - - - - - - - - - - - - - - - -->
		<div class="wrap">

			<header id="header" class="clearfix">

				<h2>
					<a href="/" id="logo"> <span class="tcolor"><?php echo $labels[logo]?></span>
					</a>
				</h2>
				<h6 class="ui-state-highlight ui-corner-all" style="float: right"><?php echo $labels['version']?></h6>
			</header>
			<!--/ #header-->
		</div>


		<!-- - - - - - - - - - - - - - end Header - - - - - - - - - - - - - - - - -->


		<!-- beging the container -->
		<div class="container">
            <?php echo $this->content; ?>
            
      </div>
		<!-- /container -->
        <?php
        echo $this->partial('layout/footer.phtml');
        ?>
    </div>
</body>
</html>