<?php require 'module/Users/view/users/utils/user_label.php';?>

<!-- - - - - - - - - - - - - - Top Panel - - - - - - - - - - - - - - - - -->

<div class="top-line clearfix  ui-corner-all">

	<div class="topcenter">
		<ul id="topleft">
			<li><a href="/info/help"><?php echo $user_labels['help']; ?> </a></li>
			<li class="ui-state-highlight ui-corner-all"><?php echo $user_labels['version']?></li>
		</ul>

		<ul id="topright">
			<li class="ui-state-default ui-corner-all"
				title="<?php echo $user_labels[logout]; ?>"><a
				href="/users/login/logout"> <span class="ui-icon ui-icon-extlink"></span>
			</a></li>
			<li class="ui-state-default ui-corner-all" id="setProfile_top"
				title="<?php echo $user_labels[userSet]; ?>"><a href="#"> <span
					class="ui-icon ui-icon-gear"></span>
			</a></li>
			<li><a><?php echo date("D Y-m-d");  ?></a></li>
			<li id="top_user_email"><?php echo $_SESSION['email'];?></li>
		</ul>
	</div>


</div>
<!--/ .top-line-->
<!-- - - - - - - - - - - - - end Top Panel - - - - - - - - - - - - - - - -->

